# Copyright 2014 Ronoaldo JLP <ronoaldo@gmail.com>
# Licensed under the Apache License, Version 2.0

module: default
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /.*
  script: _go_app