# Copyright 2014 Ronoaldo JLP <ronoaldo@gmail.com>
# Licensed under the Apache License, Version 2.0

module: backend
runtime: go
api_version: go1

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 15m

handlers:
- url: /.*
  script: _go_app